version: "2"
services:
  nginx:
    image: linuxserver/letsencrypt
    container_name: mmontes-dev-nginx
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=${PGID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=${EMAIL}
      - STAGING=${STAGING}
    volumes:
      - ./config:/config
    ports:
      - ${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}
    restart: unless-stopped
  duckdns:
    image: linuxserver/duckdns
    container_name: mmontes-dev-duckdns
    volumes:
      - "./duckdns:/config"
    environment:
      - PUID=${PGID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=true
    restart: unless-stopped