version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - "./nginx:/etc/nginx"
    network_mode: host
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_MQTT_PORT}:${NGINX_MQTT_PORT}"
    restart: always
