version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - "./nginx:/etc/nginx"
    network_mode: host
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
