apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mmontes-dev
  labels:
    app: mmontes-dev
    tier: reverse-proxy
spec:
  selector:
    app: mmontes-dev
    tier: reverse-proxy
  type: LoadBalancer
  ports:
    - port: 443
      name: https
      nodePort: 30443
    - port: 80
      name: http
      nodePort: 30080
    - port: 8080
      name: status
