apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
    - port: 9113
      targetPort: 9113
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    app: nginx-exporter
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
        - name: nginx-exporter
          image: mmontes11/nginx-prometheus-exporter
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 75m
            limits:
              memory: 64Mi
              cpu: 125m
          ports:
            - containerPort: 9113
          envFrom:
            - configMapRef:
                name: nginx-exporter
