apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: mmontes-dev
  labels:
    app: mmontes-dev
    tier: reverse-proxy
data:
  EMAIL: martin11lrx@gmail.com
  PGID: "1000"
  PUID: "1000"
  STAGING: "false"
  SUBDOMAINS: mmontes-dev
  TZ: Europe/Madrid
  URL: mmontes-dev.duckdns.org
  VALIDATION: duckdns
