apiVersion: v1
kind: Service
metadata:
  name: mosquitto-exporter
  namespace: monitoring
  labels:
    app: mosquitto-exporter
spec:
  selector:
    app: mosquitto-exporter
  ports:
    - port: 9113
      targetPort: 9113
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
  namespace: monitoring
  labels:
    app: mosquitto-exporter
spec:
  selector:
    matchLabels:
      app: mosquitto-exporter
  template:
    metadata:
      labels:
        app: mosquitto-exporter
    spec:
      containers:
        - name: mosquitto-exporter
          image: mmontes11/mosquitto-prometheus-exporter
          imagePullPolicy: Always
          resources:
            limits:
              memory: "64Mi"
              cpu: "125m"
          ports:
            - containerPort: 9113
          envFrom:
            - configMapRef:
                name: mosquitto-exporter
            - secretRef:
                name: mosquitto-exporter
