apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-exporter
  namespace: monitoring
  labels:
    app: nginx-exporter
data:
  LISTEN_ADDRESS: :9113
  NGINX_RETRIES: "10"
  NGINX_RETRY_INTERVAL: 5s
  SCRAPE_URI: http://nginx.iot:8080/nginx_status
  TELEMETRY_PATH: /metrics
  TIMEOUT: 5s
