apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  namespace: mmontes-dev
  labels:
    app: mmontes-dev
    tier: reverse-proxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
