apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-exporter
  namespace: monitoring
  labels:
    app: mosquitto-exporter
data:
  BIND_ADDRESS: 0.0.0.0:9113
  BROKER_ENDPOINT: tcp://mosquitto.iot:1883
